<?php

use Illuminate\Database\Seeder;

class TeamOrPlayerSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('team_or_players')->insert(['name' => "Bangladesh", 'image' => 'http://testdamo.cccul.com/dist/img/canada.png']);
        DB::table('team_or_players')->insert(['name' => "India", 'image' => 'http://testdamo.cccul.com/dist/img/canada.png']);
        DB::table('team_or_players')->insert(['name' => "Pakistan", 'image' => 'http://testdamo.cccul.com/dist/img/canada.png']);
        DB::table('team_or_players')->insert(['name' => "Brazil", 'image' => 'http://testdamo.cccul.com/dist/img/canada.png']);
        DB::table('team_or_players')->insert(['name' => "Japan", 'image' => 'http://testdamo.cccul.com/dist/img/canada.png']);
//        DB::table('team_or_players')->insert(['name' => "Afghanistan", 'image' => 'http://testdamo.cccul.com/dist/img/canada.png']);
//        DB::table('team_or_players')->insert(['name' => "Albania", 'image' => 'http://testdamo.cccul.com/dist/img/canada.png']);
//        DB::table('team_or_players')->insert(['name' => "Algeria", 'image' => 'http://testdamo.cccul.com/dist/img/canada.png']);
//        DB::table('team_or_players')->insert(['name' => "Andorra", 'image' => 'http://testdamo.cccul.com/dist/img/canada.png']);
//        DB::table('team_or_players')->insert(['name' => "Angola", 'image' => 'http://testdamo.cccul.com/dist/img/canada.png']);
//        DB::table('team_or_players')->insert(['name' => "Antigua and Barbuda", 'image' => 'http://testdamo.cccul.com/dist/img/canada.png']);
//        DB::table('team_or_players')->insert(['name' => "Argentina", 'image' => 'http://testdamo.cccul.com/dist/img/canada.png']);
//        DB::table('team_or_players')->insert(['name' => "Armenia", 'image' => 'http://testdamo.cccul.com/dist/img/canada.png']);
//        DB::table('team_or_players')->insert(['name' => "Australia", 'image' => 'http://testdamo.cccul.com/dist/img/canada.png']);
//        DB::table('team_or_players')->insert(['name' => "Austria", 'image' => 'http://testdamo.cccul.com/dist/img/canada.png']);
//        DB::table('team_or_players')->insert(['name' => "Austrian Empire", 'image' => 'http://testdamo.cccul.com/dist/img/canada.png']);
//        DB::table('team_or_players')->insert(['name' => "Azerbaijan", 'image' => 'http://testdamo.cccul.com/dist/img/canada.png']);
//        DB::table('team_or_players')->insert(['name' => "Baden", 'image' => 'http://testdamo.cccul.com/dist/img/canada.png']);
//        DB::table('team_or_players')->insert(['name' => "Bahamas, The", 'image' => 'http://testdamo.cccul.com/dist/img/canada.png']);
//        DB::table('team_or_players')->insert(['name' => "Bahrain", 'image' => 'http://testdamo.cccul.com/dist/img/canada.png']);
//        DB::table('team_or_players')->insert(['name' => "Bangladesh", 'image' => 'http://testdamo.cccul.com/dist/img/canada.png']);
//        DB::table('team_or_players')->insert(['name' => "Barbados", 'image' => 'http://testdamo.cccul.com/dist/img/canada.png']);
//        DB::table('team_or_players')->insert(['name' => "Bavaria*", 'image' => 'http://testdamo.cccul.com/dist/img/canada.png']);
//        DB::table('team_or_players')->insert(['name' => "Belarus", 'image' => 'http://testdamo.cccul.com/dist/img/canada.png']);
//        DB::table('team_or_players')->insert(['name' => "Belgium", 'image' => 'http://testdamo.cccul.com/dist/img/canada.png']);
//        DB::table('team_or_players')->insert(['name' => "Belize", 'image' => 'http://testdamo.cccul.com/dist/img/canada.png']);
//        DB::table('team_or_players')->insert(['name' => "Benin (Dahomey)", 'image' => 'http://testdamo.cccul.com/dist/img/canada.png']);
//        DB::table('team_or_players')->insert(['name' => "Bolivia", 'image' => 'http://testdamo.cccul.com/dist/img/canada.png']);
//        DB::table('team_or_players')->insert(['name' => "Bosnia and Herzegovina", 'image' => 'http://testdamo.cccul.com/dist/img/canada.png']);
//        DB::table('team_or_players')->insert(['name' => "Botswana", 'image' => 'http://testdamo.cccul.com/dist/img/canada.png']);
//        DB::table('team_or_players')->insert(['name' => "Brazil", 'image' => 'http://testdamo.cccul.com/dist/img/canada.png']);
//        DB::table('team_or_players')->insert(['name' => "Brunei", 'image' => 'http://testdamo.cccul.com/dist/img/canada.png']);
//        DB::table('team_or_players')->insert(['name' => "Brunswick and Lüneburg", 'image' => 'http://testdamo.cccul.com/dist/img/canada.png']);
//        DB::table('team_or_players')->insert(['name' => "Bulgaria", 'image' => 'http://testdamo.cccul.com/dist/img/canada.png']);
//        DB::table('team_or_players')->insert(['name' => "Burkina Faso (Upper Volta)", 'image' => 'http://testdamo.cccul.com/dist/img/canada.png']);
//        DB::table('team_or_players')->insert(['name' => "Burma", 'image' => 'http://testdamo.cccul.com/dist/img/canada.png']);
//        DB::table('team_or_players')->insert(['name' => "Burundi", 'image' => 'http://testdamo.cccul.com/dist/img/canada.png']);
//        DB::table('team_or_players')->insert(['name' => "Cabo Verde", 'image' => 'http://testdamo.cccul.com/dist/img/canada.png']);
//        DB::table('team_or_players')->insert(['name' => "Cambodia", 'image' => 'http://testdamo.cccul.com/dist/img/canada.png']);
//        DB::table('team_or_players')->insert(['name' => "Cameroon", 'image' => 'http://testdamo.cccul.com/dist/img/canada.png']);
//        DB::table('team_or_players')->insert(['name' => "Canada", 'image' => 'http://testdamo.cccul.com/dist/img/canada.png']);
//        DB::table('team_or_players')->insert(['name' => "Cayman Islands, The", 'image' => 'http://testdamo.cccul.com/dist/img/canada.png']);
//        DB::table('team_or_players')->insert(['name' => "Central African Republic", 'image' => 'http://testdamo.cccul.com/dist/img/canada.png']);
//        DB::table('team_or_players')->insert(['name' => "Central American Federation*", 'image' => 'http://testdamo.cccul.com/dist/img/canada.png']);
//        DB::table('team_or_players')->insert(['name' => "Chad", 'image' => 'http://testdamo.cccul.com/dist/img/canada.png']);
//        DB::table('team_or_players')->insert(['name' => "Chile", 'image' => 'http://testdamo.cccul.com/dist/img/canada.png']);
//        DB::table('team_or_players')->insert(['name' => "China", 'image' => 'http://testdamo.cccul.com/dist/img/canada.png']);
//        DB::table('team_or_players')->insert(['name' => "Colombia", 'image' => 'http://testdamo.cccul.com/dist/img/canada.png']);
//        DB::table('team_or_players')->insert(['name' => "Comoros", 'image' => 'http://testdamo.cccul.com/dist/img/canada.png']);
//        DB::table('team_or_players')->insert(['name' => "Congo Free State, The", 'image' => 'http://testdamo.cccul.com/dist/img/canada.png']);
//        DB::table('team_or_players')->insert(['name' => "Costa Rica", 'image' => 'http://testdamo.cccul.com/dist/img/canada.png']);
//        DB::table('team_or_players')->insert(['name' => "Cote d’Ivoire (Ivory Coast)", 'image' => 'http://testdamo.cccul.com/dist/img/canada.png']);
//        DB::table('team_or_players')->insert(['name' => "Croatia", 'image' => 'http://testdamo.cccul.com/dist/img/canada.png']);
//        DB::table('team_or_players')->insert(['name' => "Cuba", 'image' => 'http://testdamo.cccul.com/dist/img/canada.png']);
//        DB::table('team_or_players')->insert(['name' => "Cyprus", 'image' => 'http://testdamo.cccul.com/dist/img/canada.png']);
//        DB::table('team_or_players')->insert(['name' => "Czechia", 'image' => 'http://testdamo.cccul.com/dist/img/canada.png']);
//        DB::table('team_or_players')->insert(['name' => "Czechoslovakia", 'image' => 'http://testdamo.cccul.com/dist/img/canada.png']);
//        DB::table('team_or_players')->insert(['name' => "Democratic Republic of the Congo", 'image' => 'http://testdamo.cccul.com/dist/img/canada.png']);
//        DB::table('team_or_players')->insert(['name' => "Denmark", 'image' => 'http://testdamo.cccul.com/dist/img/canada.png']);
//        DB::table('team_or_players')->insert(['name' => "Djibouti", 'image' => 'http://testdamo.cccul.com/dist/img/canada.png']);
//        DB::table('team_or_players')->insert(['name' => "Dominica", 'image' => 'http://testdamo.cccul.com/dist/img/canada.png']);
//        DB::table('team_or_players')->insert(['name' => "Dominican Republic", 'image' => 'http://testdamo.cccul.com/dist/img/canada.png']);
//        DB::table('team_or_players')->insert(['name' => "Duchy of Parma", 'image' => 'http://testdamo.cccul.com/dist/img/canada.png']);
//        DB::table('team_or_players')->insert(['name' => "East Germany (German Democratic Republic)", 'image' => 'http://testdamo.cccul.com/dist/img/canada.png']);
//        DB::table('team_or_players')->insert(['name' => "Ecuador", 'image' => 'http://testdamo.cccul.com/dist/img/canada.png']);
//        DB::table('team_or_players')->insert(['name' => "Egypt", 'image' => 'http://testdamo.cccul.com/dist/img/canada.png']);
//        DB::table('team_or_players')->insert(['name' => "El Salvador", 'image' => 'http://testdamo.cccul.com/dist/img/canada.png']);
//        DB::table('team_or_players')->insert(['name' => "Equatorial Guinea", 'image' => 'http://testdamo.cccul.com/dist/img/canada.png']);
//        DB::table('team_or_players')->insert(['name' => "Eritrea", 'image' => 'http://testdamo.cccul.com/dist/img/canada.png']);
//        DB::table('team_or_players')->insert(['name' => "Estonia", 'image' => 'http://testdamo.cccul.com/dist/img/canada.png']);
//        DB::table('team_or_players')->insert(['name' => "Eswatini", 'image' => 'http://testdamo.cccul.com/dist/img/canada.png']);
//        DB::table('team_or_players')->insert(['name' => "Ethiopia", 'image' => 'http://testdamo.cccul.com/dist/img/canada.png']);
//        DB::table('team_or_players')->insert(['name' => "Federal Government of Germany", 'image' => 'http://testdamo.cccul.com/dist/img/canada.png']);
//        DB::table('team_or_players')->insert(['name' => "Fiji", 'image' => 'http://testdamo.cccul.com/dist/img/canada.png']);
//        DB::table('team_or_players')->insert(['name' => "Finland", 'image' => 'http://testdamo.cccul.com/dist/img/canada.png']);
//        DB::table('team_or_players')->insert(['name' => "France", 'image' => 'http://testdamo.cccul.com/dist/img/canada.png']);
//        DB::table('team_or_players')->insert(['name' => "Gabon", 'image' => 'http://testdamo.cccul.com/dist/img/canada.png']);
//        DB::table('team_or_players')->insert(['name' => "Gambia", 'image' => 'http://testdamo.cccul.com/dist/img/canada.png']);
//        DB::table('team_or_players')->insert(['name' => "Georgia", 'image' => 'http://testdamo.cccul.com/dist/img/canada.png']);
//        DB::table('team_or_players')->insert(['name' => "Germany", 'image' => 'http://testdamo.cccul.com/dist/img/canada.png']);
//        DB::table('team_or_players')->insert(['name' => "Ghana", 'image' => 'http://testdamo.cccul.com/dist/img/canada.png']);
//        DB::table('team_or_players')->insert(['name' => "Grand Duchy of Tuscany", 'image' => 'http://testdamo.cccul.com/dist/img/canada.png']);
//        DB::table('team_or_players')->insert(['name' => "Greece", 'image' => 'http://testdamo.cccul.com/dist/img/canada.png']);
//        DB::table('team_or_players')->insert(['name' => "Grenada", 'image' => 'http://testdamo.cccul.com/dist/img/canada.png']);
//        DB::table('team_or_players')->insert(['name' => "Guatemala", 'image' => 'http://testdamo.cccul.com/dist/img/canada.png']);
//        DB::table('team_or_players')->insert(['name' => "Guinea", 'image' => 'http://testdamo.cccul.com/dist/img/canada.png']);
//        DB::table('team_or_players')->insert(['name' => "Guinea-Bissau", 'image' => 'http://testdamo.cccul.com/dist/img/canada.png']);
//        DB::table('team_or_players')->insert(['name' => "Guyana", 'image' => 'http://testdamo.cccul.com/dist/img/canada.png']);
//        DB::table('team_or_players')->insert(['name' => "Haiti", 'image' => 'http://testdamo.cccul.com/dist/img/canada.png']);
//        DB::table('team_or_players')->insert(['name' => "Hanover", 'image' => 'http://testdamo.cccul.com/dist/img/canada.png']);
//        DB::table('team_or_players')->insert(['name' => "Hanseatic Republics", 'image' => 'http://testdamo.cccul.com/dist/img/canada.png']);
//        DB::table('team_or_players')->insert(['name' => "Hawaii", 'image' => 'http://testdamo.cccul.com/dist/img/canada.png']);
//        DB::table('team_or_players')->insert(['name' => "Hesse", 'image' => 'http://testdamo.cccul.com/dist/img/canada.png']);
//        DB::table('team_or_players')->insert(['name' => "Holy See", 'image' => 'http://testdamo.cccul.com/dist/img/canada.png']);
//        DB::table('team_or_players')->insert(['name' => "Honduras", 'image' => 'http://testdamo.cccul.com/dist/img/canada.png']);
//        DB::table('team_or_players')->insert(['name' => "Hungary", 'image' => 'http://testdamo.cccul.com/dist/img/canada.png']);
//        DB::table('team_or_players')->insert(['name' => "Iceland", 'image' => 'http://testdamo.cccul.com/dist/img/canada.png']);
//        DB::table('team_or_players')->insert(['name' => "India", 'image' => 'http://testdamo.cccul.com/dist/img/canada.png']);
//        DB::table('team_or_players')->insert(['name' => "Indonesia", 'image' => 'http://testdamo.cccul.com/dist/img/canada.png']);
//        DB::table('team_or_players')->insert(['name' => "Iran", 'image' => 'http://testdamo.cccul.com/dist/img/canada.png']);
//        DB::table('team_or_players')->insert(['name' => "Iraq", 'image' => 'http://testdamo.cccul.com/dist/img/canada.png']);
//        DB::table('team_or_players')->insert(['name' => "Ireland", 'image' => 'http://testdamo.cccul.com/dist/img/canada.png']);
//        DB::table('team_or_players')->insert(['name' => "Israel", 'image' => 'http://testdamo.cccul.com/dist/img/canada.png']);
//        DB::table('team_or_players')->insert(['name' => "Italy", 'image' => 'http://testdamo.cccul.com/dist/img/canada.png']);
//        DB::table('team_or_players')->insert(['name' => "Jamaica", 'image' => 'http://testdamo.cccul.com/dist/img/canada.png']);
//        DB::table('team_or_players')->insert(['name' => "Japan", 'image' => 'http://testdamo.cccul.com/dist/img/canada.png']);
//        DB::table('team_or_players')->insert(['name' => "Jordan", 'image' => 'http://testdamo.cccul.com/dist/img/canada.png']);
//        DB::table('team_or_players')->insert(['name' => "Kazakhstan", 'image' => 'http://testdamo.cccul.com/dist/img/canada.png']);
//        DB::table('team_or_players')->insert(['name' => "Kenya", 'image' => 'http://testdamo.cccul.com/dist/img/canada.png']);
//        DB::table('team_or_players')->insert(['name' => "Kingdom of Serbia/Yugoslavia", 'image' => 'http://testdamo.cccul.com/dist/img/canada.png']);
//        DB::table('team_or_players')->insert(['name' => "Kiribati", 'image' => 'http://testdamo.cccul.com/dist/img/canada.png']);
//        DB::table('team_or_players')->insert(['name' => "Korea", 'image' => 'http://testdamo.cccul.com/dist/img/canada.png']);
//        DB::table('team_or_players')->insert(['name' => "Kosovo", 'image' => 'http://testdamo.cccul.com/dist/img/canada.png']);
//        DB::table('team_or_players')->insert(['name' => "Kuwait", 'image' => 'http://testdamo.cccul.com/dist/img/canada.png']);
//        DB::table('team_or_players')->insert(['name' => "Kyrgyzstan", 'image' => 'http://testdamo.cccul.com/dist/img/canada.png']);
//        DB::table('team_or_players')->insert(['name' => "Laos", 'image' => 'http://testdamo.cccul.com/dist/img/canada.png']);
//        DB::table('team_or_players')->insert(['name' => "Latvia", 'image' => 'http://testdamo.cccul.com/dist/img/canada.png']);
//        DB::table('team_or_players')->insert(['name' => "Lebanon", 'image' => 'http://testdamo.cccul.com/dist/img/canada.png']);
//        DB::table('team_or_players')->insert(['name' => "Lesotho", 'image' => 'http://testdamo.cccul.com/dist/img/canada.png']);
//        DB::table('team_or_players')->insert(['name' => "Lew Chew (Loochoo)", 'image' => 'http://testdamo.cccul.com/dist/img/canada.png']);
//        DB::table('team_or_players')->insert(['name' => "Liberia", 'image' => 'http://testdamo.cccul.com/dist/img/canada.png']);
//        DB::table('team_or_players')->insert(['name' => "Libya", 'image' => 'http://testdamo.cccul.com/dist/img/canada.png']);
//        DB::table('team_or_players')->insert(['name' => "Liechtenstein", 'image' => 'http://testdamo.cccul.com/dist/img/canada.png']);
//        DB::table('team_or_players')->insert(['name' => "Lithuania", 'image' => 'http://testdamo.cccul.com/dist/img/canada.png']);
//        DB::table('team_or_players')->insert(['name' => "Luxembourg", 'image' => 'http://testdamo.cccul.com/dist/img/canada.png']);
//        DB::table('team_or_players')->insert(['name' => "Madagascar", 'image' => 'http://testdamo.cccul.com/dist/img/canada.png']);
//        DB::table('team_or_players')->insert(['name' => "Malawi", 'image' => 'http://testdamo.cccul.com/dist/img/canada.png']);
//        DB::table('team_or_players')->insert(['name' => "Malaysia", 'image' => 'http://testdamo.cccul.com/dist/img/canada.png']);
//        DB::table('team_or_players')->insert(['name' => "Maldives", 'image' => 'http://testdamo.cccul.com/dist/img/canada.png']);
//        DB::table('team_or_players')->insert(['name' => "Mali", 'image' => 'http://testdamo.cccul.com/dist/img/canada.png']);
//        DB::table('team_or_players')->insert(['name' => "Malta", 'image' => 'http://testdamo.cccul.com/dist/img/canada.png']);
//        DB::table('team_or_players')->insert(['name' => "Marshall Islands", 'image' => 'http://testdamo.cccul.com/dist/img/canada.png']);
//        DB::table('team_or_players')->insert(['name' => "Mauritania", 'image' => 'http://testdamo.cccul.com/dist/img/canada.png']);
//        DB::table('team_or_players')->insert(['name' => "Mauritius", 'image' => 'http://testdamo.cccul.com/dist/img/canada.png']);
//        DB::table('team_or_players')->insert(['name' => "Mecklenburg-Schwerin", 'image' => 'http://testdamo.cccul.com/dist/img/canada.png']);
//        DB::table('team_or_players')->insert(['name' => "Mecklenburg-Strelitz", 'image' => 'http://testdamo.cccul.com/dist/img/canada.png']);
//        DB::table('team_or_players')->insert(['name' => "Mexico", 'image' => 'http://testdamo.cccul.com/dist/img/canada.png']);
//        DB::table('team_or_players')->insert(['name' => "Micronesia", 'image' => 'http://testdamo.cccul.com/dist/img/canada.png']);
//        DB::table('team_or_players')->insert(['name' => "Moldova", 'image' => 'http://testdamo.cccul.com/dist/img/canada.png']);
//        DB::table('team_or_players')->insert(['name' => "Monaco", 'image' => 'http://testdamo.cccul.com/dist/img/canada.png']);
//        DB::table('team_or_players')->insert(['name' => "Mongolia", 'image' => 'http://testdamo.cccul.com/dist/img/canada.png']);
//        DB::table('team_or_players')->insert(['name' => "Montenegro", 'image' => 'http://testdamo.cccul.com/dist/img/canada.png']);
//        DB::table('team_or_players')->insert(['name' => "Morocco", 'image' => 'http://testdamo.cccul.com/dist/img/canada.png']);
//        DB::table('team_or_players')->insert(['name' => "Mozambique", 'image' => 'http://testdamo.cccul.com/dist/img/canada.png']);
//        DB::table('team_or_players')->insert(['name' => "Namibia", 'image' => 'http://testdamo.cccul.com/dist/img/canada.png']);
//        DB::table('team_or_players')->insert(['name' => "Nassau", 'image' => 'http://testdamo.cccul.com/dist/img/canada.png']);
//        DB::table('team_or_players')->insert(['name' => "Nauru", 'image' => 'http://testdamo.cccul.com/dist/img/canada.png']);
//        DB::table('team_or_players')->insert(['name' => "Nepal", 'image' => 'http://testdamo.cccul.com/dist/img/canada.png']);
//        DB::table('team_or_players')->insert(['name' => "Netherlands", 'image' => 'http://testdamo.cccul.com/dist/img/canada.png']);
//        DB::table('team_or_players')->insert(['name' => "New Zealand", 'image' => 'http://testdamo.cccul.com/dist/img/canada.png']);
//        DB::table('team_or_players')->insert(['name' => "Nicaragua", 'image' => 'http://testdamo.cccul.com/dist/img/canada.png']);
//        DB::table('team_or_players')->insert(['name' => "Niger", 'image' => 'http://testdamo.cccul.com/dist/img/canada.png']);
//        DB::table('team_or_players')->insert(['name' => "Nigeria", 'image' => 'http://testdamo.cccul.com/dist/img/canada.png']);
//        DB::table('team_or_players')->insert(['name' => "North German Confederation", 'image' => 'http://testdamo.cccul.com/dist/img/canada.png']);
//        DB::table('team_or_players')->insert(['name' => "North German Union", 'image' => 'http://testdamo.cccul.com/dist/img/canada.png']);
//        DB::table('team_or_players')->insert(['name' => "North Macedonia", 'image' => 'http://testdamo.cccul.com/dist/img/canada.png']);
//        DB::table('team_or_players')->insert(['name' => "Norway", 'image' => 'http://testdamo.cccul.com/dist/img/canada.png']);
//        DB::table('team_or_players')->insert(['name' => "Oldenburg", 'image' => 'http://testdamo.cccul.com/dist/img/canada.png']);
//        DB::table('team_or_players')->insert(['name' => "Oman", 'image' => 'http://testdamo.cccul.com/dist/img/canada.png']);
//        DB::table('team_or_players')->insert(['name' => "Orange Free State", 'image' => 'http://testdamo.cccul.com/dist/img/canada.png']);
//        DB::table('team_or_players')->insert(['name' => "Pakistan", 'image' => 'http://testdamo.cccul.com/dist/img/canada.png']);
//        DB::table('team_or_players')->insert(['name' => "Palau", 'image' => 'http://testdamo.cccul.com/dist/img/canada.png']);
//        DB::table('team_or_players')->insert(['name' => "Panama", 'image' => 'http://testdamo.cccul.com/dist/img/canada.png']);
//        DB::table('team_or_players')->insert(['name' => "Papal States", 'image' => 'http://testdamo.cccul.com/dist/img/canada.png']);
//        DB::table('team_or_players')->insert(['name' => "Papua New Guinea", 'image' => 'http://testdamo.cccul.com/dist/img/canada.png']);
//        DB::table('team_or_players')->insert(['name' => "Paraguay", 'image' => 'http://testdamo.cccul.com/dist/img/canada.png']);
//        DB::table('team_or_players')->insert(['name' => "Peru", 'image' => 'http://testdamo.cccul.com/dist/img/canada.png']);
//        DB::table('team_or_players')->insert(['name' => "Philippines", 'image' => 'http://testdamo.cccul.com/dist/img/canada.png']);
//        DB::table('team_or_players')->insert(['name' => "Piedmont-Sardinia", 'image' => 'http://testdamo.cccul.com/dist/img/canada.png']);
//        DB::table('team_or_players')->insert(['name' => "Poland", 'image' => 'http://testdamo.cccul.com/dist/img/canada.png']);
//        DB::table('team_or_players')->insert(['name' => "Portugal", 'image' => 'http://testdamo.cccul.com/dist/img/canada.png']);
//        DB::table('team_or_players')->insert(['name' => "Qatar", 'image' => 'http://testdamo.cccul.com/dist/img/canada.png']);
//        DB::table('team_or_players')->insert(['name' => "Republic of Genoa", 'image' => 'http://testdamo.cccul.com/dist/img/canada.png']);
//        DB::table('team_or_players')->insert(['name' => "Republic of Korea (South Korea)", 'image' => 'http://testdamo.cccul.com/dist/img/canada.png']);
//        DB::table('team_or_players')->insert(['name' => "Republic of the Congo", 'image' => 'http://testdamo.cccul.com/dist/img/canada.png']);
//        DB::table('team_or_players')->insert(['name' => "Romania", 'image' => 'http://testdamo.cccul.com/dist/img/canada.png']);
//        DB::table('team_or_players')->insert(['name' => "Russia", 'image' => 'http://testdamo.cccul.com/dist/img/canada.png']);
//        DB::table('team_or_players')->insert(['name' => "Rwanda", 'image' => 'http://testdamo.cccul.com/dist/img/canada.png']);
//        DB::table('team_or_players')->insert(['name' => "Saint Kitts and Nevis", 'image' => 'http://testdamo.cccul.com/dist/img/canada.png']);
//        DB::table('team_or_players')->insert(['name' => "Saint Lucia", 'image' => 'http://testdamo.cccul.com/dist/img/canada.png']);
//        DB::table('team_or_players')->insert(['name' => "Saint Vincent and the Grenadines", 'image' => 'http://testdamo.cccul.com/dist/img/canada.png']);
//        DB::table('team_or_players')->insert(['name' => "Samoa", 'image' => 'http://testdamo.cccul.com/dist/img/canada.png']);
//        DB::table('team_or_players')->insert(['name' => "San Marino", 'image' => 'http://testdamo.cccul.com/dist/img/canada.png']);
//        DB::table('team_or_players')->insert(['name' => "Sao Tome and Principe", 'image' => 'http://testdamo.cccul.com/dist/img/canada.png']);
//        DB::table('team_or_players')->insert(['name' => "Saudi Arabia", 'image' => 'http://testdamo.cccul.com/dist/img/canada.png']);
//        DB::table('team_or_players')->insert(['name' => "Schaumburg-Lippe", 'image' => 'http://testdamo.cccul.com/dist/img/canada.png']);
//        DB::table('team_or_players')->insert(['name' => "Senegal", 'image' => 'http://testdamo.cccul.com/dist/img/canada.png']);
//        DB::table('team_or_players')->insert(['name' => "Serbia", 'image' => 'http://testdamo.cccul.com/dist/img/canada.png']);
//        DB::table('team_or_players')->insert(['name' => "Seychelles", 'image' => 'http://testdamo.cccul.com/dist/img/canada.png']);
//        DB::table('team_or_players')->insert(['name' => "Sierra Leone", 'image' => 'http://testdamo.cccul.com/dist/img/canada.png']);
//        DB::table('team_or_players')->insert(['name' => "Singapore", 'image' => 'http://testdamo.cccul.com/dist/img/canada.png']);
//        DB::table('team_or_players')->insert(['name' => "Slovakia", 'image' => 'http://testdamo.cccul.com/dist/img/canada.png']);
//        DB::table('team_or_players')->insert(['name' => "Slovenia", 'image' => 'http://testdamo.cccul.com/dist/img/canada.png']);
//        DB::table('team_or_players')->insert(['name' => "Solomon Islands", 'image' => 'http://testdamo.cccul.com/dist/img/canada.png']);
//        DB::table('team_or_players')->insert(['name' => "Somalia", 'image' => 'http://testdamo.cccul.com/dist/img/canada.png']);
//        DB::table('team_or_players')->insert(['name' => "South Africa", 'image' => 'http://testdamo.cccul.com/dist/img/canada.png']);
//        DB::table('team_or_players')->insert(['name' => "South Sudan", 'image' => 'http://testdamo.cccul.com/dist/img/canada.png']);
//        DB::table('team_or_players')->insert(['name' => "Spain", 'image' => 'http://testdamo.cccul.com/dist/img/canada.png']);
//        DB::table('team_or_players')->insert(['name' => "Sri Lanka", 'image' => 'http://testdamo.cccul.com/dist/img/canada.png']);
//        DB::table('team_or_players')->insert(['name' => "Sudan", 'image' => 'http://testdamo.cccul.com/dist/img/canada.png']);
//        DB::table('team_or_players')->insert(['name' => "Suriname", 'image' => 'http://testdamo.cccul.com/dist/img/canada.png']);
//        DB::table('team_or_players')->insert(['name' => "Sweden", 'image' => 'http://testdamo.cccul.com/dist/img/canada.png']);
//        DB::table('team_or_players')->insert(['name' => "Switzerland", 'image' => 'http://testdamo.cccul.com/dist/img/canada.png']);
//        DB::table('team_or_players')->insert(['name' => "Syria", 'image' => 'http://testdamo.cccul.com/dist/img/canada.png']);
//        DB::table('team_or_players')->insert(['name' => "Tajikistan", 'image' => 'http://testdamo.cccul.com/dist/img/canada.png']);
//        DB::table('team_or_players')->insert(['name' => "Tanzania", 'image' => 'http://testdamo.cccul.com/dist/img/canada.png']);
//        DB::table('team_or_players')->insert(['name' => "Texas", 'image' => 'http://testdamo.cccul.com/dist/img/canada.png']);
//        DB::table('team_or_players')->insert(['name' => "Thailand", 'image' => 'http://testdamo.cccul.com/dist/img/canada.png']);
//        DB::table('team_or_players')->insert(['name' => "Timor-Leste", 'image' => 'http://testdamo.cccul.com/dist/img/canada.png']);
//        DB::table('team_or_players')->insert(['name' => "Togo", 'image' => 'http://testdamo.cccul.com/dist/img/canada.png']);
//        DB::table('team_or_players')->insert(['name' => "Tonga", 'image' => 'http://testdamo.cccul.com/dist/img/canada.png']);
//        DB::table('team_or_players')->insert(['name' => "Trinidad and Tobago", 'image' => 'http://testdamo.cccul.com/dist/img/canada.png']);
//        DB::table('team_or_players')->insert(['name' => "Tunisia", 'image' => 'http://testdamo.cccul.com/dist/img/canada.png']);
//        DB::table('team_or_players')->insert(['name' => "Turkey", 'image' => 'http://testdamo.cccul.com/dist/img/canada.png']);
//        DB::table('team_or_players')->insert(['name' => "Turkmenistan", 'image' => 'http://testdamo.cccul.com/dist/img/canada.png']);
//        DB::table('team_or_players')->insert(['name' => "Tuvalu", 'image' => 'http://testdamo.cccul.com/dist/img/canada.png']);
//        DB::table('team_or_players')->insert(['name' => "Two Sicilies", 'image' => 'http://testdamo.cccul.com/dist/img/canada.png']);
//        DB::table('team_or_players')->insert(['name' => "Uganda", 'image' => 'http://testdamo.cccul.com/dist/img/canada.png']);
//        DB::table('team_or_players')->insert(['name' => "Ukraine", 'image' => 'http://testdamo.cccul.com/dist/img/canada.png']);
//        DB::table('team_or_players')->insert(['name' => "Union of Soviet Socialist Republics", 'image' => 'http://testdamo.cccul.com/dist/img/canada.png']);
//        DB::table('team_or_players')->insert(['name' => "United Arab Emirates", 'image' => 'http://testdamo.cccul.com/dist/img/canada.png']);
//        DB::table('team_or_players')->insert(['name' => "United Kingdom", 'image' => 'http://testdamo.cccul.com/dist/img/canada.png']);
//        DB::table('team_or_players')->insert(['name' => "Uruguay", 'image' => 'http://testdamo.cccul.com/dist/img/canada.png']);
//        DB::table('team_or_players')->insert(['name' => "Uzbekistan", 'image' => 'http://testdamo.cccul.com/dist/img/canada.png']);
//        DB::table('team_or_players')->insert(['name' => "Vanuatu", 'image' => 'http://testdamo.cccul.com/dist/img/canada.png']);
//        DB::table('team_or_players')->insert(['name' => "Venezuela", 'image' => 'http://testdamo.cccul.com/dist/img/canada.png']);
//        DB::table('team_or_players')->insert(['name' => "Vietnam", 'image' => 'http://testdamo.cccul.com/dist/img/canada.png']);
//        DB::table('team_or_players')->insert(['name' => "Württemberg", 'image' => 'http://testdamo.cccul.com/dist/img/canada.png']);
//        DB::table('team_or_players')->insert(['name' => "Yemen", 'image' => 'http://testdamo.cccul.com/dist/img/canada.png']);
//        DB::table('team_or_players')->insert(['name' => "Zambia", 'image' => 'http://testdamo.cccul.com/dist/img/canada.png']);
//        DB::table('team_or_players')->insert(['name' => "Zimbabwe", 'image' => 'http://testdamo.cccul.com/dist/img/canada.png']);
    }
}
